site_name: Citrix XenServer 7.6 CR Software Development Kit Guide
site_description: Citrix XenServer 7.6 CR Software Development Kit Guide
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc
  - footnotes
  - meta

pages:
- Citrix XenServer 7.6 CR Software Development Kit Guide: index.md
- Getting Started: getting-started.md
- Overview: overview.md
- Using: using.md
- Using HTTP: using-http.md
- XenServer API Extensions: xs-api-extensions.md
- XenCenter API Extensions: xc-api-extensions.md
